# 2 options when creating a tournament
ADD_NEW_PLAYERS = "1"
SELECT_EXISTING_PLAYERS = "2"

# 3 options in main menu
TOURNAMENT = "1"
PLAYERS = "2"
REPORTS = "3"

# 3 options in tournament menu
CREATE_NEW_TOURNAMENT = "1"
CHOOSE_EXISTING_TOURNAMENT = "2"
MAIN_MENU = "3"

# 2 options in players menu
ADD_A_NEW_PLAYER = "1"
ADD_A_TEAM_OF_PLAYERS = "2"
MODIFY_PLAYER_RANK = "3"
SEE_THE_LIST_OF_PLAYERS = "4"
RETURN = "5"

# 8 options in report menu
LIST_OF_ALL_PLAYERS_BY_ALPHABETICAL_ORDER = "1"
LIST_OF_ALL_PLAYERS_BY_RANK = "2"
TOURNAMENT_PLAYERS_BY_ALPHABETICAL_ORDER = "3"
LIST_OF_TOURNAMENT_PLAYERS_BY_RANK = "4"
LIST_OF_ALL_PLAYERS_FROM_ALL_TOURNAMENTS = "5"
LIST_OF_ALL_ROUNDS_IN_A_TOURNAMENT = "6"
LIST_OF_ALL_MATCHS_IN_A_TOURNAMENT = "7"
RETURN_TO_THE_MAIN_MENU = "8"
